### PR TITLE
Add InplaceInputRequirement

### PR DESCRIPTION
**Pull request by tetron**
- [x] conformance tests
- [x] cwltool support

### CODE REVIEW

**Comment by sphemakh** [comment]
What is the syntax if I want to try this out?

**Comment by mr-c** [comment]
@SpheMakh This is available in v1.0 as an extension in the CWL reference implementation and those that extend it (`toil-cwl-runner`, Arvados, possibly REANA): https://github.com/common-workflow-language/common-workflow-language/issues/380#issuecomment-349598366

**Comment by tetron** [comment]
cwltool branch at https://github.com/common-workflow-language/cwltool/pull/1035

**Comment by tetron** [comment]
I don't think we should block merging this on cwl-upgrader?

**Comment by mr-c** [comment]
Please move the reminder about CWL upgrader to its repo

**Comment by tetron** [comment]
Added issue https://github.com/common-workflow-language/cwl-upgrader/issues/24

**Pull request merged**
