### PR TITLE
Remove unconnected input

### PR DESCRIPTION
**Pull request by bogdang989**
Workflow input File2 is not connected anywhere, should be removed

### CODE REVIEW

**Comment by mr-c** [comment]
Do we have a separate test for unconnected inputs?

**Comment by bogdang989** [comment]
i wasn't sure if that is even allowed? SBG right now throws a validation error if workflow graph is not connected

**Comment by ghost** [comment]
Is there a reason why we have a workflow with an unconnected input? It seems logical that this should be removed.

**Comment by mr-c** [comment]
May be left over from the development process. It is not illegal. Making it illegal is a change best left for CWL v2.0, if at all.

**Pull request closed without merging**
