### PR TITLE
Load contents max

### PR DESCRIPTION
**Pull request by tetron**
Refs https://github.com/common-workflow-language/common-workflow-language/issues/514

-  [ ] needs conformance test

### CODE REVIEW

**Review by mr-c — APPROVED** [review]

**Comment by jmchilton** [comment]
Added a conformance test but cwltool fails it... I'll continue to look into this 😢. If my conformance test proves unhelpful feel free to strip it out.

**Comment by jmchilton** [comment]
Switched my tests around locally and it doesn't seem like cwltool is truncating this down - I find some code paths where it attempts to but maybe this circumvents them somehow or maybe I don't know what I'm doing.

```
cwltest --test conformance_tests.yaml -n 191 -- --enable-dev
Test [191/209] Test loadContents maximum size.
Test failed: cwl-runner --enable-dev --outdir=/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmp80afEK --quiet tests/wf-loadContents5.cwl tests/empty.json
Test loadContents maximum size.
Compare failure expected: {
    "contains_b": false,
    "size": 1048576
}
got: {
    "contains_b": true,
    "size": 1048577
}
caused by: failed comparison for key 'contains_b': expected: false
got: true
0 tests passed, 1 failures, 0 unsupported features
```

**Comment by jmchilton** [comment]
We agreed at the 2019 Winter Boston meeting to delay increasing this limit till past 1.1 and instead clarify error conditions occur at the current limit (WIP at https://github.com/common-workflow-language/common-workflow-language/pull/822).

**Comment by mr-c** [comment]
In CWL v1.2.0-dev5, CWL expressions can create larger `File`s, but the limit for reading remains. Users should create standalone tools/scripts if they need access to more than 64KiB.

**Pull request closed without merging**
